package notifier

import (
	"fmt"
	"strings"
	"time"

	"gopkg.in/gomail.v2"
)

// EmailConfig holds the connection parameters to dial an SMTP server.
type EmailConfig struct {
	Host     string
	Port     int
	User     string
	Password string
	From     string // MAIL_FROM_ADDRESS - display name/address for the From header
}

// EmailNotifier formats and emails deployment reports.
type EmailNotifier struct {
	Config     EmailConfig
	Recipients []string // supports multiple comma-separated recipients
}

// NewEmailNotifier returns a new EmailNotifier instance.
// `to` can be a single address or comma-separated list: "a@x.com,b@y.com"
func NewEmailNotifier(cfg EmailConfig, to string) *EmailNotifier {
	var recipients []string
	for _, r := range strings.Split(to, ",") {
		r = strings.TrimSpace(r)
		if r != "" {
			recipients = append(recipients, r)
		}
	}
	return &EmailNotifier{Config: cfg, Recipients: recipients}
}

// Send fires the formatted report to all recipient email addresses.
func (e *EmailNotifier) Send(payload Payload) error {
	if len(e.Recipients) == 0 {
		return fmt.Errorf("no recipient email addresses configured")
	}
	if e.Config.Host == "" {
		return fmt.Errorf("SMTP host is empty")
	}

	m := gomail.NewMessage()

	// From address — use MAIL_FROM_ADDRESS if set, fallback to SMTP username
	fromAddr := strings.TrimSpace(e.Config.From)
	if fromAddr == "" {
		fromAddr = e.Config.User
	}
	m.SetHeader("From", fromAddr)

	// Set all recipients in the To header
	m.SetHeader("To", e.Recipients...)

	subject := fmt.Sprintf("[%s] CodeForge Deployment: %s", payload.Project, strings.ToUpper(payload.Status))
	m.SetHeader("Subject", subject)

	// Emoji indicator
	emoji := "●"
	statusColor := "#534AB7"
	switch strings.ToLower(payload.Status) {
	case "success":
		emoji = "✓"
		statusColor = "#0F6E56"
	case "failed", "error":
		emoji = "✗"
		statusColor = "#D85A30"
	case "rollback":
		emoji = "↺"
		statusColor = "#BA7517"
	}

	// HTML body
	body := fmt.Sprintf(`
<!DOCTYPE html>
<html>
<head>
    <style>
        body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; background-color: #f5f4ff; margin: 0; padding: 20px; }
        .card { background-color: #ffffff; border-radius: 8px; border-top: 4px solid %s; box-shadow: 0 4px 6px rgba(0,0,0,0.05); max-width: 600px; margin: 0 auto; overflow: hidden; padding: 24px; }
        h2 { margin-top: 0; color: #1a1a2e; }
        .status { color: %s; font-weight: bold; }
        table { width: 100%%; border-collapse: collapse; margin-top: 15px; }
        td { padding: 8px 0; border-bottom: 1px solid #f5f4ff; }
        .label { font-weight: bold; color: #534AB7; width: 140px; }
        .value { color: #1a1a2e; }
        pre { background-color: #1a1a2e; color: #f5f4ff; padding: 12px; border-radius: 4px; overflow-x: auto; font-family: monospace; font-size: 13px; }
        .footer { text-align: center; margin-top: 20px; font-size: 11px; color: #888; }
    </style>
</head>
<body>
    <div class="card">
        <h2>CodeForge Deployment Report</h2>
        <p>Your pipeline has completed with status: <span class="status">%s %s</span></p>
        <table>
            <tr>
                <td class="label">Project</td>
                <td class="value">%s</td>
            </tr>
            <tr>
                <td class="label">Trigger</td>
                <td class="value">%s</td>
            </tr>
            <tr>
                <td class="label">Duration</td>
                <td class="value">%s</td>
            </tr>
            <tr>
                <td class="label">Commit SHA</td>
                <td class="value">%s</td>
            </tr>
            <tr>
                <td class="label">Time</td>
                <td class="value">%s</td>
            </tr>
        </table>
`, statusColor, statusColor, emoji, strings.ToUpper(payload.Status), payload.Project, payload.Trigger, payload.Duration.Round(time.Millisecond).String(), formatCommitSHA(payload.CommitSHA), payload.Timestamp.Format(time.RFC1123))

	if payload.ErrorMsg != "" {
		body += fmt.Sprintf(`
        <h3 style="color: #D85A30; margin-top: 20px;">Execution Error</h3>
        <pre>%s</pre>
`, payload.ErrorMsg)
	}

	body += `
    </div>
    <div class="footer">
        Generated by CodeForge CI/CD &mdash; KhajumSanjog
    </div>
</body>
</html>
`
	m.SetBody("text/html", body)

	d := gomail.NewDialer(e.Config.Host, e.Config.Port, e.Config.User, e.Config.Password)
	return d.DialAndSend(m)
}

func formatCommitSHA(sha string) string {
	if sha == "" {
		return "N/A"
	}
	return sha
}
